version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2
    environment:
      PYTHONPATH: .
    steps:
      - checkout
      - restore_cache:
          key: pycast_{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          name: Installing Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: pycast_{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            pytest
